### PR TITLE
README: Fix typo and insert line-breaks

### PR DESCRIPTION
**Pull request by Olf0**
… where deemed acceptable.

Background: Looking at the README as rendered at [the sailfishos-chum/main frontpage](https://github.com/sailfishos-chum/main#sailfishoschum-community-repository-documentation-and-issue-tracker) now, made me wish to re-insert forced line-breaks at least at the locations where @rinigus [indicated that they are acceptable for him](https://github.com/sailfishos-chum/main/pull/48#issuecomment-1013934095): For avoiding the central web-link to run across a line end and to visually separate the FAQ questions from their answers.
Thus, when I spotted a typo, I took the chance.

### CODE REVIEW

**Comment by piggz** [comment]
I wonder if any of these work and might be preferable? https://stackoverflow.com/questions/26626256/how-to-insert-a-line-break-br-in-markdown?rq=1

**Comment by rinigus** [comment]
Thank you very much! Merging :)

**Comment by rinigus** [comment]
@piggz - looks like we cross-posted. Saw your post later as "notification".

**Comment by Olf0** [comment]
> I wonder if any of these work and might be preferable? https://stackoverflow.com/questions/26626256/how-to-insert-a-line-break-br-in-markdown?rq=1

This adds another, orthogonal dimension to the partial disagreement between rinigus and me concerning forced line-breaks: the syntax!
Actually that was not at all my point, and the way I understood rinigus, it also was not his concern.
But the specific syntax suggested there is evil IMO: Two trailing, "invisible" space characters (which will be automatically wiped away by any proper linter) or a trailing backslash, which means exactly the opposite (the forced concatenation of lines) in many programming languages (shell etc.)!

I rather stick to the explicit and specified syntax `<br />` (while `<br>` and `<br/>` also work) and respect the demarcation line drawn with rinigus. :wink:

**Comment by piggz** [comment]
Fair enough, i wont loose sleep over it :D

**Pull request merged**
