### PR TITLE
Add custom description field

### PR DESCRIPTION
**Pull request by rinigus**
Sync with the current GUI

### CODE REVIEW

**Comment by piggz** [comment]
Do we only support a subset of markdown or, the full thing like code blocks, tables?

**Comment by rinigus** [comment]
No idea, it all depends on the rendering lib. codeblocks are probably in, but with the biggish font. See https://github.com/showdownjs/showdown

**Comment by rinigus** [comment]
Found docs: https://github.com/showdownjs/showdown/wiki/Showdown's-Markdown-syntax

**Comment by piggz** [comment]
Maybe add a link to the syntax then?

**Comment by rinigus** [comment]
Link added

**Review by Olf0 — CHANGES_REQUESTED** [review]
Please merge PR #60 into this branch before merging it to the main branch.

I will gladly review this PR then.

**Comment by rinigus** [comment]
Looking forward for review

**Comment by piggz** [comment]
Reads fine to me

**Pull request merged**
